# Generated by Django 4.0.6 on 2022-07-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Valuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_valut', models.CharField(max_length=50, verbose_name='Название валюты')),
                ('mark_valut', models.CharField(max_length=3, verbose_name='Значок валюты')),
                ('type_risk', models.IntegerField(default=0, verbose_name='Тип риска')),
            ],
        ),
    ]
