# Generated by Django 4.0.6 on 2022-07-15 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_db_constraints.operations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_country', models.CharField(max_length=30, unique=True, verbose_name='Название страны')),
                ('type_risk', models.IntegerField(default=0, verbose_name='Тип риска')),
                ('date_add', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата добавления/обновления')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Valuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_valut', models.CharField(max_length=50, unique=True, verbose_name='Название валюты')),
                ('mark_valut', models.CharField(max_length=3, unique=True, verbose_name='Значок валюты')),
                ('type_risk', models.IntegerField(default=0, verbose_name='Тип риска')),
                ('date_add', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата добавления/обновления')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(verbose_name='Сумма перевода')),
                ('level_risk', models.CharField(blank=True, max_length=10, verbose_name='Уровень риска')),
                ('date_order', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата транзакции')),
                ('type_valuta_id', models.ForeignKey(db_column='type_valuta_id', on_delete=django.db.models.deletion.PROTECT, to='risk.valuta', verbose_name='Валюта')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('born_date', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('date_add_param', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата добавления/обновления')),
                ('country_id', models.ForeignKey(blank=True, db_column='country_id', default='', on_delete=django.db.models.deletion.PROTECT, to='risk.country', verbose_name='Страна')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователь доп. параметры',
                'verbose_name_plural': 'Пользователи доп. параметры',
            },
        ),
        django_db_constraints.operations.AlterConstraints(
            name='Country',
            db_constraints={'prime_risk': 'check ((type_risk <= 3) and (type_risk >= 0))'},
        ),
        django_db_constraints.operations.AlterConstraints(
            name='Employee',
            db_constraints={'age_over_18': 'check (date_part($$year$$,age(born_date::date)) >= 14)'},
        ),
        django_db_constraints.operations.AlterConstraints(
            name='Transaction',
            db_constraints={'agree_risk': 'check (level_risk in ($$Низкий$$,$$Средний$$,$$Высокий$$,$$$$))', 'count_not_zero': 'check (count > 0)'},
        ),
        django_db_constraints.operations.AlterConstraints(
            name='Valuta',
            db_constraints={'prime_risk': 'check ((type_risk <= 3) and (type_risk >= 0))'},
        ),
    ]
