# Generated by Django 4.0.6 on 2022-07-11 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_alter_valuta_options_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='user_id',
            new_name='Пользователь',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='type_valuta_id',
            new_name='Тип валюты',
        ),
    ]
