# Generated by Django 4.0.6 on 2022-07-11 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('risk', '0003_rename_user_id_transaction_пользователь_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_country', models.CharField(max_length=30, verbose_name='Название страны')),
                ('type_risk', models.IntegerField(default=0, verbose_name='Тип риска')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('born_date', models.DateTimeField(verbose_name='Дата рождения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Страна', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='risk.country')),
            ],
            options={
                'verbose_name': 'Пользователь доп. параметры',
                'verbose_name_plural': 'Пользователи доп. параметры',
            },
        ),
    ]
