# Generated by Django 4.0.6 on 2022-07-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0005_alter_employee_born_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='level_risk',
            field=models.CharField(default='', max_length=10, verbose_name='Уровень риска'),
        ),
    ]
