# Generated by Django 4.0.6 on 2022-07-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0007_alter_transaction_level_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='level_risk',
            field=models.CharField(blank=True, max_length=10, verbose_name='Уровень риска'),
        ),
    ]
