# Generated by Django 4.0.6 on 2022-07-12 18:13

from django.db import migrations
import django_db_constraints.operations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0008_alter_transaction_level_risk'),
    ]

    operations = [
        django_db_constraints.operations.AlterConstraints(
            name='employee',
            db_constraints={'age_over_18': 'check (date_part($$year$$,age(born_date::date)) >= 14)'},
        ),
    ]
