# Generated by Django 4.0.6 on 2022-07-12 18:28

from django.db import migrations, models
import django_db_constraints.operations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0009_auto_20220713_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='count',
            field=models.IntegerField(verbose_name='Сумма перевода'),
        ),
        django_db_constraints.operations.AlterConstraints(
            name='country',
            db_constraints={'prime_risk': 'check ((type_risk <= 10) and (type_risk >= 0))'},
        ),
        django_db_constraints.operations.AlterConstraints(
            name='transaction',
            db_constraints={'agree_risk': 'check(level_risk in ($$Низкий$$,$$Средний$$,$$Высокий$$))'},
        ),
        django_db_constraints.operations.AlterConstraints(
            name='valuta',
            db_constraints={'prime_risk': 'check ((type_risk <= 10) and (type_risk >= 0))'},
        ),
    ]
