# Generated by Django 4.0.6 on 2022-07-13 20:12

from django.db import migrations
import django_db_constraints.operations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0013_auto_20220713_0136'),
    ]

    operations = [
        django_db_constraints.operations.AlterConstraints(
            name='transaction',
            db_constraints={'agree_risk': 'check (level_risk in ($$Низкий$$,$$Средний$$,$$Высокий$$))', 'count_not_zero': 'check (count > 0)'},
        ),
    ]
