# Generated by Django 4.0.6 on 2022-07-13 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_db_constraints.operations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('risk', '0014_auto_20220714_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Страна',
            field=models.ForeignKey(db_column='country_id', on_delete=django.db.models.deletion.PROTECT, to='risk.country'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Пользователь',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Тип валюты',
            field=models.ForeignKey(db_column='type_valuta_id', on_delete=django.db.models.deletion.PROTECT, to='risk.valuta'),
        ),
        django_db_constraints.operations.AlterConstraints(
            name='transaction',
            db_constraints={'agree_risk': 'check (level_risk in ($$Низкий$$,$$Средний$$,$$Высокий$$,$$$$))', 'count_not_zero': 'check (count > 0)'},
        ),
    ]
