# Generated by Django 4.0.6 on 2022-07-13 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0015_auto_20220714_0316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Страна',
            new_name='country_id',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Тип валюты',
            new_name='type_valuta_id',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Пользователь',
            new_name='user_id',
        ),
    ]
