# Generated by Django 4.0.6 on 2022-07-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0017_auto_20220714_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='date_add',
            field=models.DateTimeField(null=True, verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_add_param',
            field=models.DateTimeField(null=True, verbose_name='Дата добавления параметров'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_order',
            field=models.DateTimeField(null=True, verbose_name='Дата перевода'),
        ),
        migrations.AddField(
            model_name='valuta',
            name='date_add',
            field=models.DateTimeField(null=True, verbose_name='Дата добавления'),
        ),
    ]
