# Generated by Django 4.0.6 on 2022-07-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0018_country_date_add_employee_date_add_param_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name_country',
            field=models.CharField(max_length=30, unique=True, verbose_name='Название страны'),
        ),
        migrations.AlterField(
            model_name='valuta',
            name='mark_valut',
            field=models.CharField(max_length=3, unique=True, verbose_name='Значок валюты'),
        ),
        migrations.AlterField(
            model_name='valuta',
            name='name_valut',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название валюты'),
        ),
    ]
