# Generated by Django 4.0.6 on 2022-07-14 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('risk', '0019_alter_country_name_country_alter_valuta_mark_valut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='country_id',
            field=models.ForeignKey(db_column='country_id', on_delete=django.db.models.deletion.PROTECT, to='risk.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type_valuta_id',
            field=models.ForeignKey(db_column='type_valuta_id', on_delete=django.db.models.deletion.PROTECT, to='risk.valuta', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
